version: '3.9'

services:
  php:
    build: .
    container_name: php
    depends_on:
      - db
      - phpmyadmin
    ports:
      - "80:80" # Jika kamu ingin mengakses dari host

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    ports:
      - "8080:80" # Atau port lain yang kamu inginkan untuk phpMyAdmin

volumes:
  db_data:
