version: '3.9'

services:
  php:
    build: .
    container_name: php
    depends_on:
      - db
      - phpmyadmin
    volumes:
      - php_code:/var/www/html 

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ingatsholat!
      MYSQL_DATABASE: slims
      MYSQL_USER: slims
      MYSQL_PASSWORD: Ingatdoa!
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db


volumes:
  db_data:
  php_code: 
